Added check if order history is updated when placed order
elgentos/magento2-playwright pull request #20
Opened 2024-11-14 15:47 UTC by dheesen

2024-11-18 08:38 UTC, shayfaber requested changes
@dheesen please check `tests/base/fixtures/before/slugs.json`, you forgot a comma on line 23 after declaring "orderGridSlug".

2024-11-18 09:10 UTC, shayfaber requested changes
@dheesen some feedback:

- The 'Check order history for orders' test will fail if the account does not have an address attached. When the test runs fastForward (line 12 from `tests/base/utils/Checkout.ts`), it selects the first address. This should be rewritten.
- Please also provide Gherkin syntax feature description above the test.

Please let me know when this is updated, and I'll review again.

2024-11-19 11:10 UTC, dheesen commented
@shayfaber Improved on your feedback. 👍

2024-11-20 08:33 UTC, shayfaber approved these changes

2024-11-20 08:33 UTC, merged