Gitlab 41: Overhauling refactor of code.
elgentos/magento2-playwright pull request #25
Opened 2024-12-04 15:25 UTC by shayfaber

This is a huge refactor of the code, which aims to ensure we can better adhere to Playwright standards. It also adds todo action points throughout the project, both immediately actionable items to be converted into tickets (will be done later) as well as todo's for further in the future once we've implemented storagestates to log users in and created a function utilizing API to quickly load a product into the cart.

2024-12-09 15:32 UTC, dheesen commented
@shayfaber Should we also removed the `/refactor/` folder?

2024-12-09 15:35 UTC, dheesen requested changes
Looks good. 👍

2024-12-09 15:35 UTC, dheesen commented on playwright/.auth/user.json
> +{
This file needs to be included in the `.gitignore` file.

2024-12-09 15:35 UTC, dheesen commented on tests/auth.setup.ts
> +  // End of authentication steps.
Unnecessary comment.

2024-12-09 15:35 UTC, dheesen commented on tests/auth.setup.ts
> +  // Wait until the page receives the cookies.
To which line is this referring?

2024-12-09 15:35 UTC, dheesen commented on playwright/.auth/user.json
> +{
Can you also uncommit this file?

2024-12-09 15:35 UTC, dheesen commented on tests/base/account.spec.ts
> +      const lastNameField = page.getByLabel('Last Name');
@shayfaber You don't have to do a constant when used once.

2024-12-09 15:35 UTC, dheesen commented on tests/base/account.spec.ts
> +    // await page.locator(accountSelector.accountEditAddressButtons).first().click();
Can this commented out line be removed?

2024-12-09 15:35 UTC, dheesen commented on tests/refactor/fixtures/mainmenu.page.ts
> +export class MainMenuPage {
@shayfaber Second thoughts about this naming? 😅

2024-12-10 09:25 UTC, shayfaber commented on tests/base/account.spec.ts
> +      const lastNameField = page.getByLabel('Last Name');
I'm opting to not fix these because it's in the base folder. Everything in the base folder will be replaced with what's currently in the refactor folder, so it's not necessary to update this.

2024-12-10 09:25 UTC, shayfaber commented on tests/base/account.spec.ts
> +    // await page.locator(accountSelector.accountEditAddressButtons).first().click();
I'm opting to not fix these because it's in the base folder. Everything in the base folder will be replaced with what's currently in the refactor folder, so it's not necessary to update this.

2024-12-10 09:27 UTC, shayfaber commented on tests/refactor/fixtures/mainmenu.page.ts
> +export class MainMenuPage {
Yeah it's a bit confusing that it's called a Page when it's really an element. This is the naming convention of POM in Playwright. When you create an instance, you can call it `mainmenu`. I'm assuming that's good enough but let me know if you want to rename this.

2024-12-10 09:30 UTC, shayfaber commented
> @shayfaber Should we also removed the `/refactor/` folder?

@dheesen Yes!  I've created a ticket in Gitlab to do this once this PR has been merged into main.
https://gitlab.elgentos.nl/elgentos/magento2-bdd-e2e-testing-suite/-/issues/68

2024-12-10 09:32 UTC, dheesen approved these changes

2024-12-10 09:41 UTC, merged