Gitlab-13: Add test to remove product from Cart page
elgentos/magento2-playwright pull request #29
Opened 2024-12-10 10:41 UTC by shayfaber

2024-12-10 18:01 UTC, dheesen requested changes
Small remark.

2024-12-10 18:01 UTC, dheesen commented on tests/base/cart.spec.ts
>    test('Add coupon code in cart',{ tag: ['@cart', '@coupon-code']}, async ({page}) => {
@shayfaber Looks like some random code came through 😅

2024-12-11 08:55 UTC, shayfaber commented
@dheesen fixed! Could you review this again?

2024-12-11 10:16 UTC, dheesen approved these changes

2024-12-11 10:16 UTC, merged