Gitlab 25: Product price and quantity check from PDP to Checkout
elgentos/magento2-playwright pull request #33
Opened 2024-12-23 09:50 UTC by shayfaber

2024-12-31 09:55 UTC, dheesen reviewed
@shayfaber Need some clarification about the `devtools.spec.ts`.

2024-12-31 09:55 UTC, dheesen commented on tests/base/devtools.spec.ts
@shayfaber Why is this called devtools.spec? Why can't this be combined in the minicart.spec / cart.spec?

2025-01-06 08:19 UTC, shayfaber commented on tests/base/devtools.spec.ts
I placed this in devtools because dividing it into those two spec files would require a lot of duplicate code. I am breaking convention for this though, so I totally see the argument it could be divided into those files.

2025-01-13 08:13 UTC, shayfaber commented on tests/base/devtools.spec.ts
@dheesen Fixed!

2025-01-13 12:56 UTC, dheesen requested changes

2025-01-13 12:56 UTC, dheesen commented on .gitignore
@shayfaber Why do these files need to be added here?

2025-01-13 12:56 UTC, dheesen commented on tests/base/cart.spec.ts
> +      await productPage.addSimpleProductToCart();
@shayfaber This step doesn't work, because no `url` is given.

2025-01-14 11:09 UTC, dheesen approved these changes

2025-01-14 11:09 UTC, merged